version: 2.1
# Test again
jobs:
  build:
    docker:
      - image: hunteri/terraform-packer:latest
        user: root
    steps:
      - checkout
      - run:
          name: Checkout hunter-ops master branch
          command: |
            git clone https://$GIT_USER:$GIT_PASS@github.com/hunt3ri/hunter-ops.git
      - run:
          name: Make .aws directory for credentials file
          command: |
            mkdir $HOME/.aws
      - run:
          name: Set Prod AWS Credentials
          command: |
            echo "[hunter_ops_prod]" >> ~/.aws/credentials
            echo "aws_access_key_id = $AWS_ACCESS_KEY_PROD" >> ~/.aws/credentials
            echo "aws_secret_access_key = $AWS_SECRET_KEY_PROD" >> ~/.aws/credentials
            echo "region = us-east-1" >> ~/.aws/credentials
            tail ~/.aws/credentials
      - run:
          name: Initialise terraform and set global vars file
          command: |
            cd ./hunter-ops/ops
            . ./setenv.sh hunter_ops_prod
            chmod +x ./utils/tfinit
      - run:
          name: Create vpc
          command: |
            . ./hunter-ops/ops/utils/terraform.tfvars.sh
            cd ./hunter-ops/ops/terraform/global/vpc
            /root/project/hunter-ops/ops/utils/tfinit
            terraform apply -auto-approve
      - run:
          name: Create Flask-Bootstrap ASG
          command: |
            . ./hunter-ops/ops/utils/terraform.tfvars.sh
            cd ./hunter-ops/ops/terraform/middleware/flask_bootstrap_api
            /root/project/hunter-ops/ops/utils/tfinit
            terraform apply -auto-approve

